version: "3"
services:
    ping:
        build:
            context: ./ping
        environment:
            - "OTEL_TRACES_EXPORTER=jaeger"
            - "OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250"
            - "OTEL_SERVICE_NAME=ping"
        ports:
            - "8080:8080"
        networks:
            - otel-network

    pong:
        build:
            context: ./pong
        environment:
            - "OTEL_TRACES_EXPORTER=jaeger"
            - "OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250"
            - "OTEL_SERVICE_NAME=pong"
        ports:
            - "8081:8081"
        networks:
            - otel-network

    jaeger:
        image: jaegertracing/all-in-one:1.29
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"
        networks:
            - otel-network

networks:
    otel-network:
